/* Wörterbücher. Bewusst ohne Store-Import: seed.ts braucht sie, und der Store
   importiert seed.ts — ein gemeinsamer Import würde einen Zirkel schließen. */

export type Lang = "de" | "en";

/* Das deutsche Wörterbuch ist die Vorlage. Das englische wird darauf typisiert
   — fehlt dort ein Eintrag oder hat er die falsche Signatur, bricht der Build.
   Damit kann keine Sprache still hinter der anderen zurückbleiben. */
const de = {
  app: {
    name: "PEER Routines",
    tagline: "Learn, Body, Image, Money — dein Tag in vier Säulen.",
    description:
      "Learn, Body, Image, Money — dein Tag in vier Säulen, mit Flow-Timer, Zielen und Streaks.",
  },

  common: {
    done: "Fertig",
    cancel: "Abbrechen",
    save: "Speichern",
    change: "Ändern",
    delete: "Löschen",
    add: "Neu",
    back: "Zurück",
    loading: "Lädt…",
    moment: "Moment…",
    yes: "Ja",
    no: "Nein",
    day: "Tag",
    days: "Tage",
    points: "Punkte",
    minutesShort: "Min",
    of: "von",
    today: "Heute",
    notTracked: "nicht getrackt",
    needsConnection: "Dafür braucht es eine Verbindung",
    failed: "Hat nicht geklappt",
  },

  tabs: {
    today: "Heute",
    flow: "Flow",
    progress: "Fortschritt",
    friends: "Freunde",
    you: "Du",
  },

  pillars: {
    learn: { label: "Learn", full: "Lernen & Skills", seg: "Lernen" },
    body: { label: "Body", full: "Körper & Energie", seg: "Körper" },
    image: { label: "Image", full: "Auftreten & Reichweite", seg: "Image" },
    money: { label: "Money", full: "Geld & Projekte", seg: "Geld" },
    relax: { label: "Pause", full: "Pause", seg: "Pause" },
  },

  blocks: {
    morning: "Morgen",
    school: "Schule",
    afternoon: "Nachmittag",
    evening: "Abend",
  },

  /* Sonntag zuerst, wie Date.getDay() zählt. */
  dayAbbr: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
  daysAll: "täglich",
  daysWeek: "Mo–Fr",
  daysWeekend: "Wochenende",

  today: {
    title: "Heute",
    settings: "Du",
    share: "Teilen",
    shareLabel: "Tag als Bild teilen",
    savedAsImage: "Als Bild gespeichert",
    shareFailed: "Teilen hat nicht geklappt",
    next: "Als Nächstes",
    nothingPlanned: (day: string) => `Für heute (${day}) ist keine Routine geplant.`,
    createRoutines: "Unter Du → Routinen anlegen",
    extra: "Heute extra",
    newTask: "Einmalige Aufgabe für heute",
    newTaskLabel: "Neue Aufgabe",
    deleteTask: "Aufgabe löschen",
    markOpen: "Als offen markieren",
    markDone: "Als erledigt markieren",
    checkin: "Check-in",
    energy: "Energie",
    focus: "Fokus",
    sleep: "Schlaf (h)",
    screen: "Screen (h)",
    win: "Win des Tages",
    note: "Notiz",
    autosaved: "Wird automatisch gespeichert.",
    pointsOf: (done: number, total: number) => `${done} / ${total} Punkte`,
    streakDays: (n: number) => `🔥 ${n} Tage`,
    level: (n: number) => `Level ${n}`,
    notes: {
      empty: "Heute steht nichts im System — leg unter Du Routinen an.",
      perfect: "Perfekter Tag. Genau die Sorte, die Streaks baut.",
      above: "Über der Streak-Grenze. Alles ab hier ist Bonus.",
      below: (missing: number) => `Noch ${missing} Punkte-Prozent bis zur Streak.`,
      nothing: "Noch nichts abgehakt — fang mit einer Kleinigkeit an.",
    },
    skip: {
      label: (name: string) => `${name} heute auslassen`,
      undoLabel: (name: string) => `${name} wieder einplanen`,
      hint: "Heute auslassen — zählt dann nicht ins Tagesziel",
      undoHint: "Doch wieder einplanen",
      blocked: (max: number) => `Heute schon ${max} ausgelassen`,
      tooMany: (max: number) => `Mehr als ${max} pro Tag wären geschummelt`,
      done: "Heute ausgelassen — zählt nicht ins Ziel",
      undone: "Wieder eingeplant",
    },
    week: {
      title: "Diese Woche",
      empty: "Noch nichts gesetzt — drei Richtungen reichen.",
      cta: "Schwerpunkte für diese Woche setzen",
      ctaSub: "Drei Richtungen, die diese Woche zählen",
      placeholder: (n: number) => `Schwerpunkt ${n}`,
    },
  },

  flow: {
    title: "Flow",
    subtitle: "Getaktete Sequenzen. Ein Knopf, der Rest läuft.",
    start: "Starten",
    edit: "Bearbeiten",
    share: "Teilen",
    linkCopied: "Link kopiert",
    imported: (name: string) => `„${name}“ übernommen`,
    importBroken: "Dieser Sequenz-Link ist unvollständig",
    blocks: (n: number) => `${n} Blöcke`,
    recent: "Zuletzt gelaufen",
    empty: "Noch keine Sequenz. Leg eine an oder nimm die Vorschläge.",
    addSeed: "Vorschläge übernehmen",
    pause: "Pause",
    resume: "Fortsetzen",
    skipBlock: "Überspringen",
    stop: "Beenden",
    minimize: "Minimieren",
    openRun: "Sequenz öffnen",
    nextUp: "Als Nächstes",
    finished: "Sequenz fertig",
  },

  progress: {
    title: "Fortschritt",
    switchLabel: "Ziele oder Stats",
    goals: "Ziele",
    stats: "Stats",
  },

  goals: {
    title: "Ziele",
    subtitle: "Eine Zahl, ein Datum — den Rest rechnet die App.",
    empty: "Noch kein Ziel. Eines reicht, um den Unterschied zu merken.",
    perWeek: (n: string, unit: string) => `${n} ${unit} pro Woche nötig`,
    daysLeft: (n: number) => `noch ${n} Tage`,
    overdue: "Frist vorbei",
    reached: "Erreicht",
    of: (current: string, target: string, unit: string) => `${current} / ${target} ${unit}`,
  },

  stats: {
    title: "Stats",
    subtitle: "Was du im Alltag nicht merkst.",
    tooEarly:
      "Die Zahlen hier werden ab ein paar getrackten Tagen interessant. Nach zwei Wochen siehst du, welcher Wochentag dich regelmäßig kippt und welche Säule du still fallen lässt.",
    streak: "Streak",
    bestStreak: "Beste Streak",
    avg30: "Ø Score 30 Tage",
    perfectDays: "Perfekte Tage",
    totalXp: "Gesamt-XP",
    level: "Level",
    patterns: "Muster",
    lookback: "Rückblick",
    consistency: "Konsistenz · 12 Wochen",
    trend: "Tagesscore · 14 Tage",
    balance: "Säulen-Balance · Ø 30 Tage",
    flow: "Flow · letzte 7 Tage",
    review: (week: string) => `Wochenreview · KW ${week}`,
    earlierWeeks: "Frühere Wochen",
    strongest: (p: string) => `Stärkste Säule: ${p}`,
    weakest: (p: string) => `Schwächste: ${p}`,
    flowMinutes: (n: number) => `${n} Min`,
    noFlow: "Diese Woche noch keine Flow-Zeit.",
    wins: "Wins",
    lesson: "Gelernt",
    focusNext: "Fokus nächste Woche",
  },

  insights: {
    needMore: (n: number) =>
      `Noch ${n} ${n === 1 ? "Check-in" : "Check-ins"}, dann tauchen hier Muster auf.`,
    none: "Noch keine deutlichen Muster — bisher liegen deine Tage zu eng beieinander.",
    fromDays: (n: number) => `aus ${n} Tagen`,
    disclaimer: "Das sind Zusammenhänge, keine Ursachen — beobachtet auf deinen eigenen Tagen.",
    sleepUp: (cut: string, d: number) =>
      `Mit mehr als ${cut} h Schlaf liegt dein Tagesscore ${d} Punkte höher.`,
    sleepDown: (cut: string, d: number) =>
      `An Tagen mit mehr als ${cut} h Schlaf liegt dein Score ${d} Punkte niedriger — ungewöhnlich, schau mal genauer hin.`,
    screenDown: (cut: string, d: number) =>
      `Über ${cut} h Bildschirmzeit kosten dich im Schnitt ${d} Punkte.`,
    screenUp: (cut: string, d: number) =>
      `Mehr als ${cut} h Bildschirmzeit gehen bei dir mit ${d} Punkten mehr einher.`,
    energyUp: (d: number) => `An Tagen mit hoher Energie holst du ${d} Punkte mehr.`,
    energyDown: (d: number) => `Hohe Energie fällt bei dir mit ${d} Punkten weniger zusammen.`,
    focusUp: (d: number) => `An Tagen mit hohem Fokus liegt dein Score ${d} Punkte höher.`,
    focusDown: (d: number) => `Hoher Fokus fällt bei dir mit ${d} Punkten weniger zusammen.`,
    flowUp: (cut: number, d: number) =>
      `Mit mehr als ${cut} Flow-Minuten liegt dein Score ${d} Punkte höher.`,
    flowDown: (d: number) => `Viel Flow-Zeit geht bei dir mit ${d} Punkten weniger einher.`,
    weekday: (best: string, worst: string, d: number) =>
      `${best} ist dein stärkster Tag, ${worst} dein schwächster — ${d} Punkte Unterschied.`,
  },

  lookback: {
    pick: "Tag ansehen",
    routinesThatDay: (n: number) => `${n} ${n === 1 ? "Routine" : "Routinen"} an dem Tag`,
    jokerProtected: " · per Joker geschützt",
    win: "Win des Tages",
    note: "Notiz",
    useJoker: (left: number) => `Joker einsetzen (${left} übrig)`,
    jokerUsedUp: "Joker für diesen Monat aufgebraucht",
    undoJoker: "Joker zurücknehmen",
    jokerSet: "Tag geschützt — die Serie läuft weiter",
    jokerUndone: "Joker zurückgenommen",
    shareImage: "Als Bild teilen",
  },

  routines: {
    title: "Routinen",
    subtitle: (n: number, pts: number) => `${n} Routinen · ${pts} Punkte pro voller Woche`,
    empty: "Noch keine Routine. Nimm die Vorschläge oder leg eigene an.",
    addSeed: "Vorschläge übernehmen",
    name: "Name",
    pillar: "Säule",
    block: "Tageszeit",
    weekdays: "Wochentage",
    weight: "Punkte",
    deleteHabit: "Routine löschen",
    newHabit: "Neue Routine",
    editHabit: "Routine bearbeiten",
  },

  friends: {
    title: "Freunde",
    needsAccountSub: "Erst anmelden, dann verbinden.",
    needsAccount:
      "Freunde brauchen ein Konto — sonst gibt es niemanden, mit dem sich etwas verknüpfen ließe.",
    toAccount: "Zum Konto",
    noCloud: "Ohne Supabase-Konfiguration gibt es keine Freunde-Funktion.",
    handleSub: "Ein Handle, dann kann man dich finden.",
    yourHandle: "Dein Handle",
    handleRules:
      "3–20 Zeichen, nur Kleinbuchstaben, Ziffern und Unterstrich. Freunde geben ihn ein, um dich zu finden — eine Suche über die Nutzerliste gibt es bewusst nicht.",
    secureHandle: "Handle sichern",
    profileCreated: "Profil angelegt",
    youAre: (handle: string) => `Du bist @${handle}`,
    shareHandle: "Handle",
    inviteText: (handle: string) => `Füg mich in PEER Routines hinzu: @${handle}`,
    handleCopied: "Handle kopiert",
    youToday: "Du heute",
    streakDays: (n: number) => `🔥 ${n} Tage Serie`,
    noStreak: "Noch keine Serie",
    requests: "Anfragen",
    requestSent: "Anfrage gesendet",
    wantsToConnect: (handle: string) => `@${handle} will sich verbinden`,
    accept: "Annehmen",
    decline: "Ablehnen",
    withdraw: "Abbrechen",
    withdrawn: "Zurückgezogen",
    connected: "Verbunden",
    todayHeading: "Heute",
    noneYet: "Noch niemand verbunden. Unten den Handle einer Freundin oder eines Freundes eingeben.",
    nothingShared: "hat heute noch nichts geteilt",
    streakShort: (n: number) => `${n} Tage Serie`,
    addHeading: "Hinzufügen",
    search: "Suchen",
    notFound: "Diesen Handle gibt es nicht",
    request: "Anfragen",
    privacy:
      "Freunde sehen ausschließlich deinen Tagesscore in Prozent und deine Serie. Keine Routinen, keine Notizen, keine Check-ins.",
    deleteShares: "Geteilte Stände löschen",
    sharesDeleted: "Geteilte Stände gelöscht",
    deleteSharesHint:
      "Entfernt alles, was Freunde von dir sehen. Solange ein Profil besteht, wird der heutige Stand danach wieder geteilt — willst du das dauerhaft aus, lös die Freundschaften.",
  },

  you: {
    title: "Du",
    switchLabel: "Konto oder Routinen",
    account: "Konto",
    routines: "Routinen",
    trackedDays: (n: number, date: string) => `${n} getrackte Tage · Stand ${date}`,

    profile: "Profil",
    yourName: "Dein Name",
    displayName: "Anzeigename",
    changeAvatar: "Profilbild ändern",
    since: (date: string) => ` · dabei seit ${date}`,
    avatarKind: "Art des Profilbilds",
    sigil: "Zeichen",
    animals: "Tiere",
    letter: "Buchstabe",
    others: "Sonstige",
    letterHint: "Der erste Buchstabe deines Namens auf der Akzentfarbe.",
    palettes: "Farbsätze",
    roll: "Würfeln",
    barColor: (n: number) => `Farbe der ${n}. Säule`,
    barHeight: (n: number) => `Höhe der ${n}. Säule`,
    appearsToFriends: "So erscheinst du bei Freunden.",
    accent: "Akzentfarbe",

    appSection: "App",
    installIntro:
      "Auf dem Homescreen läuft sie ohne Browserleiste, mit eigenem Icon — und startet auch ohne Netz.",

    language: "Sprache",
    languageHint:
      "Ändert die Oberfläche. Deine eigenen Routinen, Ziele und Notizen bleiben so, wie du sie eingetippt hast.",

    sync: "Sync",
    noCloud:
      "Cloud ist für diese Installation nicht eingerichtet. Die App läuft komplett lokal weiter — Konto und Geräte-Sync schaltest du frei, indem in Vercel NEXT_PUBLIC_SUPABASE_URL und NEXT_PUBLIC_SUPABASE_ANON_KEY gesetzt sind.",
    signIn: "Anmelden",
    signUp: "Konto erstellen",
    signOut: "Abmelden",
    signedOut: "Abgemeldet — deine Daten bleiben auf dem Gerät",
    email: "E-Mail",
    password: "Passwort",
    signedIn: "Angemeldet",
    accountCreated: "Konto erstellt — falls nötig, bestätige die Mail",
    forgotPassword: "Passwort vergessen?",
    resetSent: "Mail unterwegs — der Link führt zurück hierher",
    enterEmailFirst: "Erst die E-Mail eintragen",
    fillBoth: "E-Mail und Passwort ausfüllen",
    accountBenefit:
      "Mit Konto liegen deine Daten zusätzlich in deiner Datenbank und sind auf Handy und PC gleich. Ohne Konto funktioniert alles genauso — nur eben nur auf diesem Gerät.",
    changePassword: "Passwort ändern",
    fromResetMail: "Aus der Zurücksetzen-Mail — jetzt neu setzen",
    newPassword: "Neues Passwort (min. 6 Zeichen)",
    passwordChanged: "Passwort geändert",
    changeEmail: "E-Mail ändern",
    bothInboxes: "Bestätigung geht an beide Adressen",
    newEmail: "Neue E-Mail",
    confirmSent: "Bestätigungsmail unterwegs",
    deleteCloud: "Cloud-Daten löschen",
    deleteCloudHint:
      "Cloud-Daten löschen entfernt deine Zeile in der Datenbank. Auf diesem Gerät bleibt alles liegen — beim nächsten Sync würde es wieder hochgeladen. Das Anmelde-Konto selbst bleibt bestehen; das kann nur im Supabase-Dashboard entfernt werden, dafür bräuchte die App Rechte, die eine öffentliche App nicht haben darf.",
    reallyDelete: "Wirklich löschen",
    cloudDeleted: "Cloud-Daten gelöscht",
    syncOffline: "Offline — Änderungen gehen mit, sobald Netz da ist",
    syncing: "Synchronisiert…",
    syncFailed: "Sync fehlgeschlagen",
    lastSynced: (time: string) => `Zuletzt gesynct ${time}`,
    neverSynced: "Noch nicht gesynct",
    badgeOffline: "offline",
    badgeRunning: "läuft",
    badgeError: "Fehler",
    badgeOk: "ok",

    reminders: "Erinnerungen",
    reminderTitle: "Abend-Erinnerung",
    reminderOff: "Aus — ein Stupser am Abend hält die Serie am Leben",
    reminderOn: (hour: string, tz: string) => `Täglich um ${hour}:00 · ${tz}`,
    on: "An",
    off: "Aus",
    reminderSet: "Erinnerung steht",
    remindersOff: "Erinnerungen aus",
    time: "Uhrzeit",
    testNotification: "Testbenachrichtigung anzeigen",
    testFailed: "Anzeige hat nicht geklappt",
    perDevice: "Gilt für dieses Gerät. Handy und Laptop lassen sich getrennt einstellen.",
    betterInstalled: " Zuverlässiger wird es, wenn die App auf dem Homescreen liegt.",
    noPush:
      "Dieser Browser unterstützt keine Erinnerungen. Auf dem iPhone geht es nur, wenn die App über Teilen → Zum Home-Bildschirm installiert wurde.",
    noVapid: "Erinnerungen sind nicht eingerichtet — NEXT_PUBLIC_VAPID_PUBLIC_KEY fehlt.",
    remindersNeedAccount:
      "Erinnerungen brauchen ein Konto — der Server muss wissen, wohin er sie schicken soll.",

    data: "Daten",
    downloadJson: "Backup herunterladen",
    downloadJsonSub: "JSON — alles, inklusive Sequenzen und Profil",
    downloadCsv: "CSV herunterladen",
    downloadCsvSub: "Für Tabellen — ein Tag pro Zeile",
    copyBackup: "Backup kopieren",
    copyBackupSub: "Als Text, z. B. in Notizen",
    copied: "In die Zwischenablage kopiert",
    copyBlocked: "Kopieren hat der Browser blockiert",
    restore: "Backup einspielen",
    fileLoaded: "Datei geladen — jetzt einspielen",
    replaceAndImport: "Ersetzen und einspielen",
    brokenJson: "Das ist kein gültiges Backup (JSON kaputt)",
    notOurBackup: "Das sieht nicht nach einem PEER-Routines-Backup aus",
    imported: "Backup eingespielt",
    resetHint:
      "Neu anfangen löscht Routinen, Ziele, Sequenzen, Profil und alle Tage auf diesem Gerät. Vorher exportieren.",
    resetAll: "Alles löschen",
    resetDone: "Neu gestartet",
    footerLocal: "lokal gespeichert",
    footerCloud: ", optional in deiner Supabase",
  },

  install: {
    button: "Als App benutzen",
    running: "Läuft als App. ✓",
    installed: "Installiert — schau auf deinen Homescreen",
    cancelled: "Abgebrochen — geht später über das Browser-Menü",
    failed: "Hat nicht geklappt — probier das Browser-Menü",
    later: "Später",
    understood: "Verstanden",
    install: "Installieren",
    popupSub: "Eigenes Icon, keine Browserleiste, funktioniert ohne Netz.",
    popupIos: "Teilen → Zum Home-Bildschirm. Läuft danach ohne Browserleiste.",
    hintIos: "Auf den Homescreen: in Safari unten auf Teilen → Zum Home-Bildschirm.",
    hintAndroid:
      "Auf den Homescreen: Chrome oder Samsung Internet → Menü ⋮ → App installieren. Der Knopf hier erscheint, sobald der Browser die App als installierbar meldet — meist nach dem zweiten Besuch.",
  },

  net: {
    offline: "Offline — alles läuft weiter, Sync holt nach",
    newVersion: "Neue Version bereit",
    reload: "Neu laden",
    noConnection: "Keine Verbindung.",
    tableMissing:
      "Die Tabelle app_state fehlt — das SQL aus supabase/schema.sql wurde noch nicht ausgeführt.",
    sessionExpired: "Sitzung abgelaufen — bitte neu anmelden.",
    denied: "Die Datenbank verweigert den Zugriff — prüfe die RLS-Policies.",
    unknown: "Unbekannter Fehler",
  },

  auth: {
    invalidLogin: "E-Mail oder Passwort stimmt nicht.",
    notConfirmed: "Bestätige zuerst die E-Mail, die wir dir geschickt haben.",
    alreadyRegistered: "Diese E-Mail hat schon ein Konto — melde dich einfach an.",
    passwordShort: "Das Passwort braucht mindestens 6 Zeichen.",
    invalidEmail: "Diese E-Mail-Adresse sieht nicht richtig aus.",
    rateLimit: "Zu viele Versuche. Warte kurz und probier es nochmal.",
    network: "Keine Verbindung zum Server.",
    noCloud: "Cloud ist nicht eingerichtet.",
    handleTaken: "Der Handle ist schon vergeben.",
    handleInvalid: "Handle: 3–20 Zeichen, nur a–z, 0–9 und _.",
    columnsMissing:
      "Der Datenbank fehlen die Spalten avatar und sigil — supabase/friends.sql erneut ausführen.",
    alreadyLinked: "Ihr seid schon verbunden oder eine Anfrage läuft.",
    noPermission:
      "Benachrichtigungen sind für diese Seite blockiert — das lässt sich nur in den Browser-Einstellungen zurücknehmen.",
    noConsent: "Ohne Erlaubnis keine Erinnerung.",
    noPushSupport: "Dieser Browser kann keine Erinnerungen.",
    noPushKey: "Der Push-Schlüssel fehlt in der Konfiguration.",
    subIncomplete: "Das Abo kam unvollständig zurück.",
  },

  seed: {
    habits: [
      "Pünktlich aufstehen",
      "Wasser + Frühstück",
      "5 Min Tagesplan schreiben",
      "Im Unterricht mitschreiben",
      "Einmal melden / etwas sagen",
      "Mit jemandem Neuem reden",
      "Hausaufgaben zuerst",
      "Training / Sport",
      "30 Min Skill üben",
      "1 Post / Video / Foto",
      "1 Aktion für Geld",
      "Ausgaben notiert",
      "Handy weg, 30 Min vor Schlaf",
      "15 Min lesen",
    ],
    goals: ["Lernstunden diese Season", "Trainings absolviert", "Posts veröffentlicht", "Gespart"],
    routines: [
      { name: "Power Hour", segs: ["Lesen", "Aufstehen & bewegen", "Lernen", "Workout", "Chill"] },
      { name: "Study Sprint", segs: ["Fokus", "Pause", "Fokus", "Pause"] },
      { name: "Morgen-Kickstart", segs: ["Bewegen", "Tag planen", "Content-Idee"] },
      { name: "Money Block", segs: ["Angebote / Nachrichten", "Pause", "Umsetzen"] },
    ],
  },
};

/* Das englische Wörterbuch wird auf diese Form typisiert. Fehlt dort ein
   Eintrag oder stimmt eine Signatur nicht, bricht der Build — genau das ist
   der Zweck. Ohne "as const" verbreitert TypeScript die Literale selbst zu
   string, sodass "Done" und "Fertig" beide passen. */
type Dict = typeof de;

const en: Dict = {
  app: {
    name: "PEER Routines",
    tagline: "Learn, Body, Image, Money — your day in four pillars.",
    description:
      "Learn, Body, Image, Money — your day in four pillars, with a flow timer, goals and streaks.",
  },

  common: {
    done: "Done",
    cancel: "Cancel",
    save: "Save",
    change: "Change",
    delete: "Delete",
    add: "New",
    back: "Back",
    loading: "Loading…",
    moment: "One moment…",
    yes: "Yes",
    no: "No",
    day: "day",
    days: "days",
    points: "points",
    minutesShort: "min",
    of: "of",
    today: "Today",
    notTracked: "not tracked",
    needsConnection: "That needs a connection",
    failed: "That didn't work",
  },

  tabs: {
    today: "Today",
    flow: "Flow",
    progress: "Progress",
    friends: "Friends",
    you: "You",
  },

  pillars: {
    learn: { label: "Learn", full: "Learning & skills", seg: "Learn" },
    body: { label: "Body", full: "Body & energy", seg: "Body" },
    image: { label: "Image", full: "Presence & reach", seg: "Image" },
    money: { label: "Money", full: "Money & projects", seg: "Money" },
    relax: { label: "Break", full: "Break", seg: "Break" },
  },

  blocks: {
    morning: "Morning",
    school: "School",
    afternoon: "Afternoon",
    evening: "Evening",
  },

  dayAbbr: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  daysAll: "every day",
  daysWeek: "Mon–Fri",
  daysWeekend: "weekends",

  today: {
    title: "Today",
    settings: "You",
    share: "Share",
    shareLabel: "Share day as image",
    savedAsImage: "Saved as image",
    shareFailed: "Sharing didn't work",
    next: "Up next",
    nothingPlanned: (day: string) => `Nothing is planned for today (${day}).`,
    createRoutines: "Add routines under You → Routines",
    extra: "Extra today",
    newTask: "One-off task for today",
    newTaskLabel: "New task",
    deleteTask: "Delete task",
    markOpen: "Mark as open",
    markDone: "Mark as done",
    checkin: "Check-in",
    energy: "Energy",
    focus: "Focus",
    sleep: "Sleep (h)",
    screen: "Screen (h)",
    win: "Win of the day",
    note: "Note",
    autosaved: "Saved automatically.",
    pointsOf: (done: number, total: number) => `${done} / ${total} points`,
    streakDays: (n: number) => `🔥 ${n} days`,
    level: (n: number) => `Level ${n}`,
    notes: {
      empty: "Nothing set up yet — add routines under You.",
      perfect: "Perfect day. Exactly the kind that builds streaks.",
      above: "Above the streak line. Everything from here is bonus.",
      below: (missing: number) => `${missing} more points-percent to the streak.`,
      nothing: "Nothing ticked yet — start with something small.",
    },
    skip: {
      label: (name: string) => `Skip ${name} today`,
      undoLabel: (name: string) => `Put ${name} back`,
      hint: "Skip today — it won't count toward the daily target",
      undoHint: "Put it back",
      blocked: (max: number) => `Already skipped ${max} today`,
      tooMany: (max: number) => `More than ${max} a day would be cheating`,
      done: "Skipped today — doesn't count toward the target",
      undone: "Back in the plan",
    },
    week: {
      title: "This week",
      empty: "Nothing set yet — three directions are enough.",
      cta: "Set priorities for this week",
      ctaSub: "Three directions that matter this week",
      placeholder: (n: number) => `Priority ${n}`,
    },
  },

  flow: {
    title: "Flow",
    subtitle: "Timed sequences. One button, the rest runs itself.",
    start: "Start",
    edit: "Edit",
    share: "Share",
    linkCopied: "Link copied",
    imported: (name: string) => `“${name}” added`,
    importBroken: "This sequence link is incomplete",
    blocks: (n: number) => `${n} blocks`,
    recent: "Recently run",
    empty: "No sequence yet. Create one or take the suggestions.",
    addSeed: "Use suggestions",
    pause: "Pause",
    resume: "Resume",
    skipBlock: "Skip",
    stop: "Stop",
    minimize: "Minimise",
    openRun: "Open sequence",
    nextUp: "Up next",
    finished: "Sequence complete",
  },

  progress: {
    title: "Progress",
    switchLabel: "Goals or stats",
    goals: "Goals",
    stats: "Stats",
  },

  goals: {
    title: "Goals",
    subtitle: "A number and a date — the app does the rest.",
    empty: "No goal yet. One is enough to feel the difference.",
    perWeek: (n: string, unit: string) => `${n} ${unit} per week needed`,
    daysLeft: (n: number) => `${n} days left`,
    overdue: "Past due",
    reached: "Reached",
    of: (current: string, target: string, unit: string) => `${current} / ${target} ${unit}`,
  },

  stats: {
    title: "Stats",
    subtitle: "What you don't notice day to day.",
    tooEarly:
      "These numbers get interesting after a few tracked days. Two weeks in, you'll see which weekday keeps tipping you over and which pillar you quietly let slide.",
    streak: "Streak",
    bestStreak: "Best streak",
    avg30: "Avg score 30 days",
    perfectDays: "Perfect days",
    totalXp: "Total XP",
    level: "Level",
    patterns: "Patterns",
    lookback: "Look back",
    consistency: "Consistency · 12 weeks",
    trend: "Daily score · 14 days",
    balance: "Pillar balance · avg 30 days",
    flow: "Flow · last 7 days",
    review: (week: string) => `Weekly review · week ${week}`,
    earlierWeeks: "Earlier weeks",
    strongest: (p: string) => `Strongest pillar: ${p}`,
    weakest: (p: string) => `Weakest: ${p}`,
    flowMinutes: (n: number) => `${n} min`,
    noFlow: "No flow time yet this week.",
    wins: "Wins",
    lesson: "Learned",
    focusNext: "Focus next week",
  },

  insights: {
    needMore: (n: number) =>
      `${n} more ${n === 1 ? "check-in" : "check-ins"} and patterns will show up here.`,
    none: "No clear patterns yet — your days still sit too close together.",
    fromDays: (n: number) => `from ${n} days`,
    disclaimer: "These are connections, not causes — observed on your own days.",
    sleepUp: (cut: string, d: number) =>
      `With more than ${cut} h of sleep your daily score is ${d} points higher.`,
    sleepDown: (cut: string, d: number) =>
      `On days with more than ${cut} h of sleep your score is ${d} points lower — unusual, worth a closer look.`,
    screenDown: (cut: string, d: number) =>
      `More than ${cut} h of screen time costs you ${d} points on average.`,
    screenUp: (cut: string, d: number) =>
      `More than ${cut} h of screen time goes together with ${d} more points for you.`,
    energyUp: (d: number) => `On high-energy days you collect ${d} more points.`,
    energyDown: (d: number) => `High energy coincides with ${d} fewer points for you.`,
    focusUp: (d: number) => `On high-focus days your score is ${d} points higher.`,
    focusDown: (d: number) => `High focus coincides with ${d} fewer points for you.`,
    flowUp: (cut: number, d: number) =>
      `With more than ${cut} flow minutes your score is ${d} points higher.`,
    flowDown: (d: number) => `A lot of flow time goes together with ${d} fewer points for you.`,
    weekday: (best: string, worst: string, d: number) =>
      `${best} is your strongest day, ${worst} your weakest — ${d} points apart.`,
  },

  lookback: {
    pick: "View a day",
    routinesThatDay: (n: number) => `${n} ${n === 1 ? "routine" : "routines"} that day`,
    jokerProtected: " · protected by a joker",
    win: "Win of the day",
    note: "Note",
    useJoker: (left: number) => `Use a joker (${left} left)`,
    jokerUsedUp: "No jokers left this month",
    undoJoker: "Take the joker back",
    jokerSet: "Day protected — the streak continues",
    jokerUndone: "Joker taken back",
    shareImage: "Share as image",
  },

  routines: {
    title: "Routines",
    subtitle: (n: number, pts: number) => `${n} routines · ${pts} points per full week`,
    empty: "No routines yet. Take the suggestions or add your own.",
    addSeed: "Use suggestions",
    name: "Name",
    pillar: "Pillar",
    block: "Time of day",
    weekdays: "Weekdays",
    weight: "Points",
    deleteHabit: "Delete routine",
    newHabit: "New routine",
    editHabit: "Edit routine",
  },

  friends: {
    title: "Friends",
    needsAccountSub: "Sign in first, then connect.",
    needsAccount: "Friends need an account — otherwise there's nobody to connect to.",
    toAccount: "Go to account",
    noCloud: "Without Supabase configured there is no friends feature.",
    handleSub: "Pick a handle so people can find you.",
    yourHandle: "Your handle",
    handleRules:
      "3–20 characters, lowercase letters, digits and underscore only. Friends type it in to find you — there is deliberately no way to browse the user list.",
    secureHandle: "Claim handle",
    profileCreated: "Profile created",
    youAre: (handle: string) => `You are @${handle}`,
    shareHandle: "Handle",
    inviteText: (handle: string) => `Add me on PEER Routines: @${handle}`,
    handleCopied: "Handle copied",
    youToday: "You today",
    streakDays: (n: number) => `🔥 ${n} day streak`,
    noStreak: "No streak yet",
    requests: "Requests",
    requestSent: "Request sent",
    wantsToConnect: (handle: string) => `@${handle} wants to connect`,
    accept: "Accept",
    decline: "Decline",
    withdraw: "Withdraw",
    withdrawn: "Withdrawn",
    connected: "Connected",
    todayHeading: "Today",
    noneYet: "Nobody connected yet. Enter a friend's handle below.",
    nothingShared: "hasn't shared anything today",
    streakShort: (n: number) => `${n} day streak`,
    addHeading: "Add",
    search: "Search",
    notFound: "No such handle",
    request: "Request",
    privacy:
      "Friends only see your daily score as a percentage and your streak. No routines, no notes, no check-ins.",
    deleteShares: "Delete shared scores",
    sharesDeleted: "Shared scores deleted",
    deleteSharesHint:
      "Removes everything friends can see of you. As long as a profile exists, today's score will be shared again — to stop it for good, end the friendships.",
  },

  you: {
    title: "You",
    switchLabel: "Account or routines",
    account: "Account",
    routines: "Routines",
    trackedDays: (n: number, date: string) => `${n} tracked days · as of ${date}`,

    profile: "Profile",
    yourName: "Your name",
    displayName: "Display name",
    changeAvatar: "Change profile picture",
    since: (date: string) => ` · here since ${date}`,
    avatarKind: "Kind of profile picture",
    sigil: "Sigil",
    animals: "Animals",
    letter: "Letter",
    others: "Other",
    letterHint: "The first letter of your name on your accent colour.",
    palettes: "Palettes",
    roll: "Shuffle",
    barColor: (n: number) => `Colour of pillar ${n}`,
    barHeight: (n: number) => `Height of pillar ${n}`,
    appearsToFriends: "This is how friends see you.",
    accent: "Accent colour",

    appSection: "App",
    installIntro:
      "On your home screen it runs without a browser bar, with its own icon — and starts without a connection.",

    language: "Language",
    languageHint:
      "Changes the interface. Your own routines, goals and notes stay exactly as you typed them.",

    sync: "Sync",
    noCloud:
      "The cloud isn't set up for this installation. The app keeps working entirely locally — account and device sync unlock once NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY are set in Vercel.",
    signIn: "Sign in",
    signUp: "Create account",
    signOut: "Sign out",
    signedOut: "Signed out — your data stays on this device",
    email: "Email",
    password: "Password",
    signedIn: "Signed in",
    accountCreated: "Account created — confirm the email if prompted",
    forgotPassword: "Forgot your password?",
    resetSent: "Email on its way — the link brings you back here",
    enterEmailFirst: "Enter your email first",
    fillBoth: "Fill in email and password",
    accountBenefit:
      "With an account your data also lives in your database and stays the same on phone and computer. Without one everything works just the same — only on this device.",
    changePassword: "Change password",
    fromResetMail: "From the reset email — set a new one now",
    newPassword: "New password (min. 6 characters)",
    passwordChanged: "Password changed",
    changeEmail: "Change email",
    bothInboxes: "Confirmation goes to both addresses",
    newEmail: "New email",
    confirmSent: "Confirmation email on its way",
    deleteCloud: "Delete cloud data",
    deleteCloudHint:
      "Deleting cloud data removes your row in the database. Everything stays on this device — the next sync would upload it again. The sign-in account itself remains; only the Supabase dashboard can remove that, which would need permissions a public app must not have.",
    reallyDelete: "Really delete",
    cloudDeleted: "Cloud data deleted",
    syncOffline: "Offline — changes go up as soon as you're back online",
    syncing: "Syncing…",
    syncFailed: "Sync failed",
    lastSynced: (time: string) => `Last synced ${time}`,
    neverSynced: "Not synced yet",
    badgeOffline: "offline",
    badgeRunning: "running",
    badgeError: "error",
    badgeOk: "ok",

    reminders: "Reminders",
    reminderTitle: "Evening reminder",
    reminderOff: "Off — a nudge in the evening keeps the streak alive",
    reminderOn: (hour: string, tz: string) => `Daily at ${hour}:00 · ${tz}`,
    on: "On",
    off: "Off",
    reminderSet: "Reminder is set",
    remindersOff: "Reminders off",
    time: "Time",
    testNotification: "Show a test notification",
    testFailed: "Couldn't show it",
    perDevice: "Applies to this device. Phone and laptop can be set separately.",
    betterInstalled: " It gets more reliable once the app sits on your home screen.",
    noPush:
      "This browser can't do reminders. On iPhone it only works once the app is installed via Share → Add to Home Screen.",
    noVapid: "Reminders aren't configured — NEXT_PUBLIC_VAPID_PUBLIC_KEY is missing.",
    remindersNeedAccount:
      "Reminders need an account — the server has to know where to send them.",

    data: "Data",
    downloadJson: "Download backup",
    downloadJsonSub: "JSON — everything, sequences and profile included",
    downloadCsv: "Download CSV",
    downloadCsvSub: "For spreadsheets — one day per row",
    copyBackup: "Copy backup",
    copyBackupSub: "As text, e.g. into your notes",
    copied: "Copied to clipboard",
    copyBlocked: "The browser blocked copying",
    restore: "Restore a backup",
    fileLoaded: "File loaded — now restore it",
    replaceAndImport: "Replace and restore",
    brokenJson: "That isn't a valid backup (broken JSON)",
    notOurBackup: "That doesn't look like a PEER Routines backup",
    imported: "Backup restored",
    resetHint:
      "Starting over deletes routines, goals, sequences, profile and every day on this device. Export first.",
    resetAll: "Delete everything",
    resetDone: "Started over",
    footerLocal: "stored locally",
    footerCloud: ", optionally in your Supabase",
  },

  install: {
    button: "Use as an app",
    running: "Running as an app. ✓",
    installed: "Installed — check your home screen",
    cancelled: "Cancelled — you can do it later from the browser menu",
    failed: "That didn't work — try the browser menu",
    later: "Later",
    understood: "Got it",
    install: "Install",
    popupSub: "Own icon, no browser bar, works offline.",
    popupIos: "Share → Add to Home Screen. It runs without a browser bar after that.",
    hintIos: "To your home screen: in Safari tap Share → Add to Home Screen.",
    hintAndroid:
      "To your home screen: Chrome or Samsung Internet → menu ⋮ → Install app. The button here appears once the browser reports the app as installable — usually after your second visit.",
  },

  net: {
    offline: "Offline — everything keeps working, sync catches up",
    newVersion: "New version ready",
    reload: "Reload",
    noConnection: "No connection.",
    tableMissing:
      "The app_state table is missing — the SQL from supabase/schema.sql hasn't been run yet.",
    sessionExpired: "Session expired — please sign in again.",
    denied: "The database refused access — check the RLS policies.",
    unknown: "Unknown error",
  },

  auth: {
    invalidLogin: "That email or password isn't right.",
    notConfirmed: "Confirm the email we sent you first.",
    alreadyRegistered: "That email already has an account — just sign in.",
    passwordShort: "The password needs at least 6 characters.",
    invalidEmail: "That email address doesn't look right.",
    rateLimit: "Too many attempts. Wait a moment and try again.",
    network: "No connection to the server.",
    noCloud: "The cloud isn't set up.",
    handleTaken: "That handle is already taken.",
    handleInvalid: "Handle: 3–20 characters, only a–z, 0–9 and _.",
    columnsMissing:
      "The database is missing the avatar and sigil columns — run supabase/friends.sql again.",
    alreadyLinked: "You're already connected or a request is pending.",
    noPermission:
      "Notifications are blocked for this site — that can only be undone in the browser settings.",
    noConsent: "No permission, no reminder.",
    noPushSupport: "This browser can't do reminders.",
    noPushKey: "The push key is missing from the configuration.",
    subIncomplete: "The subscription came back incomplete.",
  },

  seed: {
    habits: [
      "Get up on time",
      "Water + breakfast",
      "5 min day plan",
      "Take notes in class",
      "Speak up once",
      "Talk to someone new",
      "Homework first",
      "Training / sport",
      "30 min skill practice",
      "1 post / video / photo",
      "1 action for money",
      "Expenses logged",
      "Phone away, 30 min before sleep",
      "15 min reading",
    ],
    goals: ["Study hours this season", "Workouts completed", "Posts published", "Saved"],
    routines: [
      { name: "Power Hour", segs: ["Read", "Get up & move", "Study", "Workout", "Chill"] },
      { name: "Study Sprint", segs: ["Focus", "Break", "Focus", "Break"] },
      { name: "Morning Kickstart", segs: ["Move", "Plan the day", "Content idea"] },
      { name: "Money Block", segs: ["Offers / messages", "Break", "Execute"] },
    ],
  },
};

export const DICTS: Record<Lang, Dict> = { de, en };
export type { Dict };

/** Was der Browser bevorzugt. Auf dem Server gibt es kein navigator — dort
 *  fällt es auf Deutsch zurück, was nie sichtbar wird, weil die Oberfläche
 *  hinter <Hydrated> erst nach dem Laden aus localStorage rendert. */
export function detectLang(): Lang {
  if (typeof navigator === "undefined") return "de";
  return navigator.language?.toLowerCase().startsWith("de") ? "de" : "en";
}

export const dictFor = (lang: Lang): Dict => DICTS[lang];
